server:
  port: 8080
spring:
  zipkin:
    baseUrl: http://${HOST_SERVER_URL:localhost}:9411/zipkin/
  application:
    name: product-management-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${HOST_SERVER_URL:localhost}:3306/product-management-service-db
    password: Chiran1994#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    import: configserver:http://${HOST_SERVER_URL:localhost}:9296
logging:
  file:
    name: E:/logs/product-management-service.log

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}