server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shopping-app-microservices-realm
      client:
        registration:
          keycloak:
            client-id: shopping-app-client
            client-secret: yAXXyo7uPcGNy1kthyQhH5kV3d4b9Ect
            clientName: Keycloak
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri : http://localhost:8181/realms/shopping-app-microservices-realm

  application:
    name: order-management-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/order-management-service-db
    password: Chiran1994#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    import: configserver:http://localhost:9296

logging:
  file:
    name: E:/logs/order-management-service.log

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}