apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: chiranwettewa/api-gateway-service
        ports:
        - containerPort: 9090
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-service
  ports:
  - port: 80
    targetPort: 9090

