apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-service
spec:
  selector:
    matchLabels:
      app: product-management-service
  template:
    metadata:
      labels:
        app: product-management-service
    spec:
      containers:
      - name: product-management-service
        image: chiranwettewa/product-management-service
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm

---

apiVersion: v1
kind: Service
metadata:
  name: product-management-service-svc
spec:
  selector:
    app: product-management-service
  ports:
  - port: 80
    targetPort: 8080

