server:
  port: 8081
spring:
  zipkin:
    baseUrl: http://${HOST_SERVER_URL:localhost}:9411/zipkin/
  application:
    name: payment-management-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${HOST_SERVER_URL:localhost}:3306/payment-management-service-db
    password: Chiran1994#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    import: configserver:http://${HOST_SERVER_URL:localhost}:9296
logging:
  file:
    name: E:/logs/payment-management-service.log

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
